
server:
  port: 8092

logging:
  level:
   #不同目录下的日志可配置不同级别
   org.springfromework.web: INFO
   com.gysoft: debug
  #采用相对路径方式将日志文件输出到【log/myspringboot.log】
  file: log/code-generate.log
  #采用绝对路径方式将日志文件输出到【/Users/wang/Downloads/myspringboot.log】
  #file: /Users/wang/Downloads/myspringboot.log
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

spring:
    datasource:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        name: testCode
        #url: jdbc:mysql://192.168.1.231:3306/gy_project?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
        username: gyadmin
        password: Gy(!Djz!159

        #配置多数据源
        druid:
          # 初始化大小，最小，最大
          maxActive: 20
          initialSize: 1
          # 配置获取连接等待超时的时间
          maxWait: 60000
          minIdle: 1
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filter:
             stat:
                 # 慢SQL记录
                 log-slow-sql: true
                 # 显示时间超过1000ms的sql
                 slow-sql-millis: 1000
                 # 合并sql
                 merge-sql: true
             wall:
                 config:
                     multi-statement-allow: true
          stat-view-servlet:
             enabled: true
             url-pattern: /druid/*
             #login-username: admin
             #login-password: admin

          # 合并多个DruidDataSource的监控数据
          useGlobalDataSourceStat: true

    # Jackson配置，格式化日期
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别。现在使用多数据源，下面配置注释
#mybatis:
#  mapper-locations: classpath:mybatis/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.gysoft.codegenerate.model # 注意：对应实体类的路径




